"""GitHub Issues API client."""
from __future__ import annotations

import json
import logging

import requests

from lambdas.shared.config import Config
from lambdas.shared.models import ErrorEntry, ErrorAnalysis

logger = logging.getLogger(__name__)

SEVERITY_EMOJI = {
    "critical": "\U0001f534",  # red circle
    "high": "\U0001f7e0",      # orange circle
    "medium": "\U0001f7e1",    # yellow circle
    "low": "\U0001f7e2",       # green circle
}

ISSUE_TEMPLATE = """## Error Details
- **Service**: `{service}`
- **Severity**: {severity_emoji} {severity}
- **Category**: {category}
- **First seen**: {timestamp}
- **Fingerprint**: `{fingerprint}`

### Error Message
```
{message}
```

### Stack Trace
```java
{stack_trace}
```

---

## AI Root Cause Analysis
{root_cause}

### Affected Files
{affected_files}

### Suggested Fix
{suggested_fix}

### Confidence: {confidence}%

---
_Generated by [AI Error Monitor](https://github.com/spherecorp-kr/ai-error-monitor)_
"""


def create_issue(
    error: ErrorEntry,
    analysis: ErrorAnalysis,
    github_owner: str,
    github_repo: str,
) -> str | None:
    """Create a GitHub issue for the analyzed error. Returns issue URL or None."""
    # Check for duplicate issues first
    existing = _find_duplicate_issue(error, github_owner, github_repo)
    if existing:
        logger.info("Duplicate issue found: %s", existing)
        _add_comment(existing, error, github_owner, github_repo)
        return existing

    title = f"[Auto] {analysis.summary or error.message[:80]}"
    if len(title) > 120:
        title = title[:117] + "..."

    body = ISSUE_TEMPLATE.format(
        service=error.service,
        severity_emoji=SEVERITY_EMOJI.get(analysis.severity, ""),
        severity=analysis.severity.upper(),
        category=analysis.category,
        timestamp=error.timestamp,
        fingerprint=error.fingerprint,
        message=error.message[:500],
        stack_trace=error.stack_trace[:2000] if error.stack_trace else "N/A",
        root_cause=analysis.root_cause or "Analysis not available",
        affected_files="\n".join(f"- `{f}`" for f in analysis.affected_files) or "N/A",
        suggested_fix=analysis.suggested_fix or "No fix suggested",
        confidence=int(analysis.confidence * 100),
    )

    labels = [
        "auto-detected",
        f"severity:{analysis.severity}",
        f"service:{error.service}",
    ]
    if analysis.category != "Unknown":
        labels.append(f"category:{analysis.category}")

    url = f"https://api.github.com/repos/{github_owner}/{github_repo}/issues"
    headers = {
        "Authorization": f"Bearer {Config.GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json",
    }
    payload = {
        "title": title,
        "body": body,
        "labels": labels,
    }

    try:
        resp = requests.post(url, headers=headers, json=payload, timeout=15)
        if resp.status_code == 201:
            issue_url = resp.json()["html_url"]
            logger.info("Created issue: %s", issue_url)
            return issue_url
        else:
            logger.error("Failed to create issue: HTTP %d - %s", resp.status_code, resp.text)
            # If labels don't exist, retry without them
            if resp.status_code == 422 and "label" in resp.text.lower():
                payload["labels"] = ["auto-detected"]
                resp = requests.post(url, headers=headers, json=payload, timeout=15)
                if resp.status_code == 201:
                    return resp.json()["html_url"]
    except Exception as e:
        logger.error("Failed to create GitHub issue: %s", e)

    return None


def _find_duplicate_issue(
    error: ErrorEntry, github_owner: str, github_repo: str
) -> str | None:
    """Search for existing issue with same fingerprint."""
    url = f"https://api.github.com/search/issues"
    headers = {
        "Authorization": f"Bearer {Config.GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json",
    }
    query = f'repo:{github_owner}/{github_repo} is:issue is:open "{error.fingerprint}" label:auto-detected'

    try:
        resp = requests.get(url, headers=headers, params={"q": query}, timeout=10)
        if resp.status_code == 200:
            items = resp.json().get("items", [])
            if items:
                return items[0]["html_url"]
    except Exception as e:
        logger.error("Failed to search issues: %s", e)

    return None


def _add_comment(
    issue_url: str, error: ErrorEntry, github_owner: str, github_repo: str
) -> None:
    """Add a comment to an existing issue for a recurring error."""
    # Extract issue number from URL
    issue_number = issue_url.rstrip("/").split("/")[-1]
    url = f"https://api.github.com/repos/{github_owner}/{github_repo}/issues/{issue_number}/comments"
    headers = {
        "Authorization": f"Bearer {Config.GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json",
    }
    body = f"**Recurring error detected** at `{error.timestamp}`\n\nFingerprint: `{error.fingerprint}`\nService: `{error.service}`"

    try:
        requests.post(url, headers=headers, json={"body": body}, timeout=10)
    except Exception as e:
        logger.error("Failed to add comment: %s", e)
